//! Generated gateway bootstrap for sdkwork-payment.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_payment_service_host::PaymentServiceHost;
use sdkwork_web_bootstrap::ContractFallbackConfig;
use std::sync::Arc;

pub struct ApiAssembly {
    pub router: Router,
}

pub async fn assemble_api_router(host: Arc<PaymentServiceHost>) -> ApiAssembly {
    assemble_api_router(host).await
}

pub async fn assemble_api_router(
    host: Arc<PaymentServiceHost>,
) -> ApiAssembly {
    let mut router = Router::new();
    router =
        router.merge(sdkwork_routes_payment_app_api::gateway_mount_business(host.clone()).await);
    router = router.merge(sdkwork_routes_payment_backend_api::gateway_mount_business(host).await);
    ApiAssembly { router }
}

pub async fn assemble_backend_business_router(
    host: Arc<PaymentServiceHost>,
) -> ApiAssembly {
    ApiAssembly {
        router: sdkwork_routes_payment_backend_api::gateway_mount_business(host).await,
    }
}

/// C17 修复：构造组合的 contract fallback config。
///
/// 合并 app-api 与 backend-api 两个 route manifest 的所有 (method, path) 对，
/// 供 `service_router` 挂载为 axum `fallback`：
/// - manifest 内声明但运行时未挂载 handler 的路径 → 501 Problem+json
/// - 完全未知的路径 → 404 Problem+json
///
/// 这样即使某些 manifest 路由尚未实现 handler，客户端也能得到符合 RFC 9457 的
/// 标准错误响应，而非 axum 默认的空 404。
pub fn gateway_contract_fallback_config() -> ContractFallbackConfig {
    let app_manifest = sdkwork_routes_payment_app_api::gateway_route_manifest();
    let backend_manifest = sdkwork_routes_payment_backend_api::gateway_route_manifest();

    let mut config = ContractFallbackConfig::from_manifest(&app_manifest);
    config.manifest_paths.extend(
        ContractFallbackConfig::from_manifest(&backend_manifest)
            .manifest_paths
            .into_iter(),
    );
    config
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn assembly_contract_fallback_contains_both_api_surfaces() {
        let config = gateway_contract_fallback_config();
        assert_eq!(51, config.manifest_paths.len());
        assert!(config.contains("POST", "/app/v3/api/payments/intents"));
        assert!(config.contains("GET", "/backend/v3/api/payments/certificates"));
    }
}
