//! Generated gateway bootstrap for sdkwork-payment.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_payment_service_host::PaymentServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<PaymentServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_payment_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_payment_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
