use sdkwork_commerce_contract_service::CommerceServiceContract;

pub fn payment_service_contract() -> CommerceServiceContract {
    CommerceServiceContract::new(
        "payment",
        "commerce.payment",
        vec![
            "payments.intents.create",
            "payments.intents.attempts.create",
            "payments.providerAccounts.create",
            "refunds.create",
            "recharges.orders.create",
        ],
        vec![
            "payments.methods.list",
            "payments.providers.list",
            "payments.providerAccounts.list",
            "payments.channels.list",
            "payments.routeRules.list",
            "payments.intents.list",
            "payments.intents.retrieve",
            "payments.attempts.list",
            "payments.attempts.retrieve",
            "payments.webhookEvents.list",
            "payments.reconciliationRuns.list",
            "refunds.list",
            "refunds.retrieve",
            "recharges.packages.list",
            "recharges.orders.list",
            "recharges.orders.retrieve",
            "commerceReports.paymentReconciliation.retrieve",
            "commerceReports.refunds.list",
        ],
        vec![
            crate::ports::PAYMENT_REPOSITORY_PORT,
            crate::ports::PAYMENT_PROVIDER_PORT,
            crate::ports::IDEMPOTENCY_REPOSITORY_PORT,
        ],
        true,
    )
}
